apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-intro
  labels:
    component: homework
  namespace: homework
spec:
  initContainers:
  - name: init-otus-first-hw
    image: busybox:1.28
    command: ['sh', '-c', "wget -O /init/index.html https://example.dwweb.ru/index.html;"]
    volumeMounts:
    - mountPath: /init
      name: shared-volume

  containers:
  - name: otus-firs-hw 
    image: docker.angie.software/angie:latest
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command: ['sh', '-s', "rm -f /init/index.html"]
    volumeMounts:
    - mountPath: /homework
      name: shared-volume
    - name: angie-config
      mountPath: /etc/angie/angie.conf
      subPath: angie.conf
    - name: angie-config
      mountPath: /etc/angie/http.d/default.conf
      subPath: default.conf

  volumes:
  - name: shared-volume
    emptyDir:
      sizeLimit: 5Mi
  - name: angie-config
    configMap:
      name: angie-config
