apiVersion: v1
kind: ConfigMap
metadata:
  name: angie-config
  namespace: {{ .Values.namespace.name }} 
data:
  angie.conf: |
    #    user angie;
    worker_processes 1;
    error_log /tmp/error.log;
    pid /tmp/angie.pid;
    include /usr/share/angie/modules/*.conf;
    events{
      worker_connections 1024;
    }

    http{
      server_tokens off;
      charset UTF-8;
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 4096;
      include /etc/angie/mime.types;
      default_type application/octet-stream;
      include /etc/angie/http.d/*.conf;
    }

  default.conf: |
    server {
    listen 8000 default_server;

    server_name _;

    location / {
        root /homework;
        autoindex on;
        allow all;
      }

    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: check-metrics
  namespace: {{ .Values.namespace.name }}
data:
  checkMetrics.sh: |
    KUBEAPI=https://kubernetes.default.svc;
    SA=/var/run/secrets/kubernetes.io/serviceaccount/;
    CACERT=${SA}ca.crt;
    TOKEN=$(cat ${SA}token);
    NAMESPACE=$(cat ${SA}namespace);
    touch /homework/metrics.html;
    curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${KUBEAPI}/metrics > /homework/metrics.html;


