apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-templating.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubernetes-templating.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "kubernetes-templating.selectorLabels" . | nindent 4 }}
