apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: webserver-fast-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain # default value is Delete
